name: build-docusaurus-docs

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: website
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          # cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build website
        run: yarn build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          # `gh-pages` 브랜치에 게시할 결과물을 빌드합니다.
          publish_dir: ./website/build
          # 다음 줄에서는 `gh-pages` 브랜치에 배포하기 위해
          # 공식 GH-Actions 봇에 커밋 권한을 할당합니다.
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # 아래 2개 필드를 지정하지 않으면 GH 액션 봇이 기본적으로 사용됩니다.
          # 자신의 자격증명으로 교체할 수 있습니다.
          # user_name: github-actions[bot]
          # user_email: 41898282+github-actions[bot]@users.noreply.github.com