name: CI
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      - uses: actions/checkout@master
      - uses: redkubes/docusaurus-deploy-action@v1.2
        with:
          source-folder: website
          git-user: daeho-gn
          git-password: ${{ secrets.GITHUB_TOKEN }}
          deployment-branch: gh-pages
